const storageKey = "we-set-office-console";
const sessionKey = "we-set-session";
const views = ["dashboard", "clients", "quotes", "items", "installations", "accounting", "users"];
const admin = { id: "owner", email: "info@weset.co.uk", password: "", name: "WeSet Admin", role: "Owner", permissions: views, active: true };
const catalog = [
  ["desktop-pc", "Desktop computer", "IT equipment", 720, "each"],
  ["laptop", "Laptop", "IT equipment", 950, "each"],
  ["monitor", "Monitor", "IT equipment", 180, "each"],
  ["desk", "Office desk", "Furniture", 260, "each"],
  ["task-chair", "Task chair", "Furniture", 190, "each"],
  ["meeting-table", "Meeting room table", "Furniture", 850, "each"],
  ["floor-plan", "Room layout plan", "Services", 650, "per project"],
  ["delivery", "Delivery and handling", "Services", 450, "per project"],
  ["onsite-setup", "On-site setup day", "Services", 900, "per day"]
].map(([id, name, category, unitCost, unit]) => ({ id, name, category, unitCost, unit, defaultQuantity: 1, supplier: category === "Services" ? "WeSet" : "Standard supplier", code: id.toUpperCase(), leadTime: "Scheduled", description: `${name} for office setup.` }));
const starter = {
  users: [admin],
  catalog,
  clients: [
    { id: "client-1", company: "Northline Finance", contact: "Amelia Grant", email: "amelia.grant@example.com", phone: "020 7946 0181", site: "12 King Street, Manchester", notes: "Needs quiet meeting rooms and 32 desk positions." },
    { id: "client-2", company: "Brightpath Legal", contact: "Samir Patel", email: "samir.patel@example.com", phone: "0113 555 0148", site: "The Exchange, Leeds", notes: "New second floor office. Access by goods lift only." }
  ],
  expenses: [
    { id: "expense-1", date: "2026-06-03", category: "Supplier purchases", payee: "Furniture supplier", amount: 4200, notes: "Desks and chairs." },
    { id: "expense-2", date: "2026-06-05", category: "Delivery", payee: "Courier partner", amount: 680, notes: "Delivery costs." }
  ],
  quotes: []
};
starter.quotes = [
  makeQuote("Q-1001", "client-1", "12 King Street, Manchester", 6, 32, "2026-06-12", "Sent", "Scheduled", "2026-06-10", [["desktop-pc", 32], ["monitor", 32], ["desk", 32], ["task-chair", 32], ["onsite-setup", 5]]),
  makeQuote("Q-1002", "client-2", "The Exchange, Leeds", 4, 20, "2026-06-20", "Draft", "Not scheduled", "", [["desk", 20], ["task-chair", 20], ["floor-plan", 1]])
];
let state = loadState();
let activeView = viewFromLocation() || "dashboard";
let selectedQuoteItems = [];
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const els = {};
[
  "loginScreen", "loginForm", "loginError", "pageTitle", "searchInput", "metrics", "pendingQuotes", "upcomingInstalls", "clientsTable", "quoteClient", "quoteForm", "premises", "addressLine1", "addressLine2", "addressCity", "addressPostcode", "addressPreview", "addressStatus", "clientSite", "clientAddressLine1", "clientAddressLine2", "clientAddressCity", "clientAddressPostcode", "clientAddressPreview", "clientAddressStatus", "catalogSelect", "selectedItems", "quoteTotalPreview", "quoteList", "quoteStatusFilter", "installStatusFilter", "installBoard", "catalogList", "usersTable", "accountingMetrics", "accountingMargin", "accountsSummary", "expenseForm", "expenseDate", "expenseCategory", "expensePayee", "expenseAmount", "expenseNotes", "salesTable", "expensesTable", "expenseBreakdown", "monthlyAccounts", "clientDialog", "clientForm", "userDialog", "userForm", "itemDialog", "itemForm", "quoteDialog", "quoteEmailPreview", "quoteEmailText", "emailQuoteLink", "nextAction"
].forEach((id) => els[id] = $(`#${id}`));

bindEvents();
resetQuoteForm();
if (els.expenseDate) els.expenseDate.value = todayPlus(0);
updateAddressPreview(clientAddressFields());
updateAuthView();
render();

function bindEvents() {
  els.loginForm?.addEventListener("submit", login);
  $("#logoutBtn")?.addEventListener("click", () => { localStorage.removeItem(sessionKey); updateAuthView(); });
  $$('[data-view]').forEach((b) => b.addEventListener("click", () => switchView(b.dataset.view)));
  $$('[data-view-link]').forEach((b) => b.addEventListener("click", () => switchView(b.dataset.viewLink)));
  window.addEventListener("hashchange", () => currentSession() && switchView(viewFromLocation() || activeView, { updateHash: false }));
  $("#newClientBtn")?.addEventListener("click", openClientDialog);
  $("#addClientInlineBtn")?.addEventListener("click", openClientDialog);
  $("#quickQuoteBtn")?.addEventListener("click", () => switchView("quotes"));
  $("#closeClientDialog")?.addEventListener("click", () => els.clientDialog.close());
  $("#newUserBtn")?.addEventListener("click", openUserDialog);
  $("#closeUserDialog")?.addEventListener("click", () => els.userDialog.close());
  $("#closeQuoteDialog")?.addEventListener("click", () => els.quoteDialog.close());
  $("#resetQuoteFormBtn")?.addEventListener("click", resetQuoteForm);
  $("#checkAddressBtn")?.addEventListener("click", checkAddressOnGoogleMaps);
  $("#lookupAddressBtn")?.addEventListener("click", () => lookupPostcodeAddress(setupAddressFields(), "setup"));
  $("#lookupClientAddressBtn")?.addEventListener("click", () => lookupPostcodeAddress(clientAddressFields(), "company"));
  $("#addCatalogItemBtn")?.addEventListener("click", addSelectedCatalogItem);
  $("#newItemBtn")?.addEventListener("click", () => openItemDialog(false));
  $("#openItemDialogFromQuoteBtn")?.addEventListener("click", () => openItemDialog(true));
  $("#closeItemDialog")?.addEventListener("click", () => els.itemDialog.close());
  $("#copyQuoteBtn")?.addEventListener("click", () => navigator.clipboard?.writeText(els.quoteEmailText.value));
  $("#copyQuoteHtmlBtn")?.addEventListener("click", () => navigator.clipboard?.writeText(els.quoteEmailPreview.innerText));
  els.searchInput?.addEventListener("input", render);
  els.quoteStatusFilter?.addEventListener("change", renderQuotes);
  els.installStatusFilter?.addEventListener("change", renderInstallations);
  els.selectedItems?.addEventListener("input", updateSelectedItemsFromInputs);
  els.selectedItems?.addEventListener("click", removeSelectedItem);
  ["#addressLine1", "#addressLine2", "#addressCity", "#addressPostcode"].forEach((s) => $(s)?.addEventListener("input", () => updateAddressPreview(setupAddressFields())));
  ["#clientAddressLine1", "#clientAddressLine2", "#clientAddressCity", "#clientAddressPostcode"].forEach((s) => $(s)?.addEventListener("input", () => updateAddressPreview(clientAddressFields())));
  els.clientForm?.addEventListener("submit", saveClient);
  els.quoteForm?.addEventListener("submit", saveQuote);
  els.userForm?.addEventListener("submit", saveUser);
  els.itemForm?.addEventListener("submit", saveItem);
  els.expenseForm?.addEventListener("submit", saveExpense);
  els.expensesTable?.addEventListener("click", deleteExpense);
}
function makeQuote(id, clientId, premises, rooms, workstations, requiredDate, status, installStatus, installDate, pairs) { return { id, clientId, premises, rooms, workstations, requiredDate, status, installStatus, installDate, notes: "", items: pairs.map(([itemId, quantity]) => ({ ...catalog.find((i) => i.id === itemId), quantity })) }; }
function loadState() { const saved = localStorage.getItem(storageKey); const loaded = saved ? JSON.parse(saved) : structuredClone(starter); loaded.users = mergeUsers(loaded.users || []); loaded.catalog = mergeCatalog(loaded.catalog || []); loaded.clients ||= []; loaded.quotes ||= []; loaded.expenses ||= []; return loaded; }
function saveState() { localStorage.setItem(storageKey, JSON.stringify(state)); }
function mergeUsers(users) { const byEmail = new Map([[admin.email, admin]]); users.forEach((u) => byEmail.set(u.email, { ...admin, ...u, permissions: mergePermissions(u.permissions || []), active: u.active !== false })); return [...byEmail.values()]; }
function mergePermissions(saved) { const set = new Set([...(saved || [])]); if (!set.size || set.has("users")) views.forEach((v) => set.add(v)); return [...set].filter((v) => views.includes(v)); }
function mergeCatalog(saved) { const map = new Map(catalog.map((i) => [i.id, i])); saved.forEach((i) => map.set(i.id, { ...map.get(i.id), ...i })); return [...map.values()]; }
function login(event) { event.preventDefault(); const email = $("#loginEmail").value.trim().toLowerCase(); const password = $("#loginPassword").value; let user = state.users.find((u) => u.email === email && u.password === password && u.active); if (!user && email === admin.email && password === admin.password) { user = admin; state.users = mergeUsers([admin, ...state.users.filter((u) => u.email !== admin.email)]); saveState(); } if (!user) { els.loginError.textContent = "Email or password is incorrect."; return; } localStorage.setItem(sessionKey, JSON.stringify({ id: user.id, email: user.email, name: user.name, loggedInAt: new Date().toISOString() })); els.loginError.textContent = ""; updateAuthView(); }
function currentSession() { const saved = localStorage.getItem(sessionKey); if (!saved) return null; const session = JSON.parse(saved); return { ...session, user: state.users.find((u) => u.id === session.id && u.active) || admin }; }
function currentUser() { return currentSession()?.user || null; }
function canAccess(view) { return Boolean(currentUser()?.permissions?.includes(view)); }
function firstAllowedView() { return currentUser()?.permissions?.find((v) => views.includes(v)) || "dashboard"; }
function updateAuthView() { const loggedIn = Boolean(currentSession()); els.loginScreen?.classList.toggle("is-hidden", loggedIn); applyAccess(); if (loggedIn) switchView(canAccess(activeView) ? activeView : firstAllowedView(), { updateHash: false }); }
function applyAccess() { const user = currentUser(); $$(".nav-item").forEach((b) => b.hidden = !user?.permissions?.includes(b.dataset.view)); $$('[data-view-link]').forEach((b) => b.hidden = !canAccess(b.dataset.viewLink)); const quick = $("#quickQuoteBtn"); if (quick) quick.disabled = !canAccess("quotes"); const addClient = $("#newClientBtn"); if (addClient) addClient.hidden = !canAccess("clients"); }
function switchView(view, opts = {}) { activeView = canAccess(view) ? view : firstAllowedView(); $$(".view").forEach((s) => s.classList.remove("is-visible")); $(`#${activeView}View`)?.classList.add("is-visible"); $$(".nav-item").forEach((b) => b.classList.toggle("is-active", b.dataset.view === activeView)); els.pageTitle.textContent = viewLabel(activeView); if (opts.updateHash !== false && location.hash !== `#${activeView}`) history.replaceState(null, "", `#${activeView}`); render(); }
function viewFromLocation() { const hash = location.hash.replace("#", "").trim(); if (views.includes(hash)) return hash; const path = location.pathname.split("/").filter(Boolean).pop()?.replace(".html", "") || ""; return views.includes(path) ? path : ""; }
function render() { renderClientSelect(); renderCatalogSelect(); renderSelectedItems(); renderDashboard(); renderClients(); renderQuotes(); renderItems(); renderUsers(); renderInstallations(); renderAccounting(); renderNextAction(); }
function renderDashboard() { const total = state.quotes.reduce((s, q) => s + quoteCosts(q).total, 0); els.metrics.innerHTML = [["Clients", state.clients.length], ["Pending quotes", state.quotes.filter((q) => ["Draft", "Sent"].includes(q.status)).length], ["Active installs", state.quotes.filter((q) => q.installStatus !== "Complete").length], ["Pipeline value", money(total)]].map(metric).join(""); els.pendingQuotes.innerHTML = state.quotes.filter((q) => ["Draft", "Sent"].includes(q.status)).slice(0, 4).map(renderQuoteCard).join("") || empty("No pending quotes."); els.upcomingInstalls.innerHTML = state.quotes.filter((q) => q.installDate && q.installStatus !== "Complete").map(renderInstallCard).join("") || empty("No installations scheduled."); }
function renderClients() { els.clientsTable.innerHTML = filteredClients().map((c) => `<tr><td><strong>${esc(c.company)}</strong><p class="meta">${esc(c.notes || "No notes")}</p></td><td>${esc(c.contact)}<p class="meta">${esc(c.email)}</p></td><td>${esc(c.site)}</td><td>${esc(c.phone)}</td><td>${state.quotes.filter((q) => q.clientId === c.id && q.installStatus !== "Complete").length}</td><td><button class="secondary" data-new-quote="${c.id}" type="button">Quote</button></td></tr>`).join("") || `<tr><td colspan="6">${empty("No clients match your search.")}</td></tr>`; $$('[data-new-quote]').forEach((b) => b.addEventListener("click", () => { switchView("quotes"); els.quoteClient.value = b.dataset.newQuote; fillAddressFromText(getClient(b.dataset.newQuote).site); })); }
function renderClientSelect() { els.quoteClient.innerHTML = state.clients.map((c) => `<option value="${c.id}">${esc(c.company)}</option>`).join(""); }
function renderCatalogSelect() { const groups = state.catalog.reduce((g, i) => ((g[i.category] ||= []).push(i), g), {}); els.catalogSelect.innerHTML = Object.entries(groups).map(([cat, items]) => `<optgroup label="${esc(cat)}">${items.map((i) => `<option value="${i.id}">${esc(i.name)} - ${money(i.unitCost)}</option>`).join("")}</optgroup>`).join(""); }
function renderQuotes() { const status = els.quoteStatusFilter.value; const quotes = filteredQuotes().filter((q) => status === "all" || q.status === status); els.quoteList.innerHTML = quotes.map(renderQuoteCard).join("") || empty("No quotes match your filters."); bindQuoteActions(); }
function renderQuoteCard(q) { const c = getClient(q.clientId), costs = quoteCosts(q), items = quoteItems(q); return `<article class="quote-card"><div class="card-top"><div><h3>${esc(q.id)} - ${esc(c.company)}</h3><p class="meta">${q.workstations} workstations, ${q.rooms} rooms<br>${esc(q.premises)}</p></div><span class="badge ${cls(q.status)}">${esc(q.status)}</span></div><p class="meta">${items.slice(0, 4).map((i) => `${i.quantity}x ${esc(i.name)}`).join(", ")}</p><p class="meta">Required ${date(q.requiredDate)} | Total ${money(costs.total)}</p><div class="card-actions"><button class="secondary" data-send-quote="${q.id}" type="button">Prepare email</button><button class="ghost" data-status="${q.id}:Sent" type="button">Mark sent</button><button class="ghost" data-status="${q.id}:Accepted" type="button">Accept</button><button class="ghost" data-status="${q.id}:Declined" type="button">Decline</button></div></article>`; }
function bindQuoteActions() { $$('[data-send-quote]').forEach((b) => b.addEventListener("click", () => showQuoteEmail(b.dataset.sendQuote))); $$('[data-status]').forEach((b) => b.addEventListener("click", () => { const [id, status] = b.dataset.status.split(":"); updateQuote(id, { status }); })); }
function renderInstallations() { const status = els.installStatusFilter.value; const quotes = state.quotes.filter((q) => status === "all" || q.installStatus === status); els.installBoard.innerHTML = quotes.map(renderInstallCard).join("") || empty("No installations match your filters."); $$('[data-install]').forEach((b) => b.addEventListener("click", () => { const [id, installStatus] = b.dataset.install.split(":"); updateQuote(id, { installStatus, installDate: installStatus === "Scheduled" ? prompt("Installation date (YYYY-MM-DD)", todayPlus(14)) || "" : getQuote(id).installDate }); })); }
function renderInstallCard(q) { const c = getClient(q.clientId); return `<article class="install-card"><div class="card-top"><div><h3>${esc(c.company)}</h3><p class="meta">${esc(q.id)} | ${q.installDate ? date(q.installDate) : "Date needed"}</p></div><span class="badge ${cls(q.installStatus)}">${esc(q.installStatus)}</span></div><p class="meta">${esc(q.premises)}</p><div class="card-actions"><button class="secondary" data-install="${q.id}:Scheduled" type="button">Schedule</button><button class="ghost" data-install="${q.id}:In progress" type="button">Start</button><button class="ghost" data-install="${q.id}:Complete" type="button">Complete</button></div></article>`; }
function renderItems() { const query = els.searchInput.value.trim().toLowerCase(); els.catalogList.innerHTML = state.catalog.filter((i) => !query || Object.values(i).join(" ").toLowerCase().includes(query)).map((i) => `<article class="catalog-item"><div><h3>${esc(i.name)}</h3><p class="meta">${esc(i.description)}<br>${esc(i.supplier)} | ${esc(i.code)} | ${esc(i.leadTime)}</p></div><div><span class="badge ${cls(i.category)}">${esc(i.category)}</span><strong>${money(i.unitCost)}</strong><p class="meta">${esc(i.unit)}</p></div></article>`).join("") || empty("No items match your search."); }
function renderUsers() { els.usersTable.innerHTML = state.users.map((u) => `<tr><td><strong>${esc(u.name)}</strong><p class="meta">${esc(u.email)}</p></td><td>${esc(u.role)}</td><td>${(u.permissions || []).map(viewLabel).join(", ")}</td><td><span class="badge ${u.active ? "Accepted" : "Declined"}">${u.active ? "Active" : "Inactive"}</span></td></tr>`).join(""); }
function renderAccounting() { if (!els.accountingMetrics) return; const sales = state.quotes.reduce((s, q) => s + quoteCosts(q).total, 0), supply = state.quotes.reduce((s, q) => s + quoteCosts(q).supply, 0), services = state.quotes.reduce((s, q) => s + quoteCosts(q).services, 0), expenses = totalExpenses(), profit = sales - expenses, margin = sales ? Math.round(profit / sales * 100) : 0; els.accountingMetrics.innerHTML = [["Sales", money(sales)], ["Expenses", money(expenses)], ["Profit", money(profit)], ["Margin", `${margin}%`]].map(metric).join(""); els.accountingMargin.textContent = `Margin ${margin}%`; els.accountingMargin.className = `badge ${profit >= 0 ? "Complete" : "Declined"}`; els.accountsSummary.innerHTML = [["Supply sales", supply], ["Services sales", services], ["Total sales", sales], ["Recorded expenses", expenses], ["Estimated profit", profit]].map(([l, v], i, a) => `<div class="account-line ${i === a.length - 1 ? "total" : ""}"><span>${esc(l)}</span><strong>${money(v)}</strong></div>`).join(""); renderSalesTable(); renderExpensesTable(); renderExpenseBreakdown(); renderMonthlyAccounts(); }
function renderSalesTable() { els.salesTable.innerHTML = state.quotes.map((q) => { const c = getClient(q.clientId), costs = quoteCosts(q); return `<tr><td>${esc(q.id)}</td><td>${esc(c.company)}</td><td><span class="badge ${cls(q.status)}">${esc(q.status)}</span></td><td>${money(costs.supply)}</td><td>${money(costs.services)}</td><td><strong>${money(costs.total)}</strong></td></tr>`; }).join("") || `<tr><td colspan="6">${empty("No quote sales yet.")}</td></tr>`; }
function renderExpensesTable() { els.expensesTable.innerHTML = [...state.expenses].sort((a, b) => b.date.localeCompare(a.date)).map((e) => `<tr><td>${date(e.date)}</td><td>${esc(e.category)}</td><td>${esc(e.payee)}</td><td><strong>${money(e.amount)}</strong></td><td><button class="ghost" data-delete-expense="${e.id}" type="button">Delete</button></td></tr>`).join("") || `<tr><td colspan="5">${empty("No expenses recorded yet.")}</td></tr>`; }
function renderExpenseBreakdown() { const totals = state.expenses.reduce((g, e) => ((g[e.category] = (g[e.category] || 0) + Number(e.amount || 0)), g), {}); els.expenseBreakdown.innerHTML = Object.entries(totals).sort((a, b) => b[1] - a[1]).map(([c, a]) => `<div class="account-line"><span>${esc(c)}</span><strong>${money(a)}</strong></div>`).join("") || empty("No category totals yet."); }
function renderMonthlyAccounts() { const months = {}; state.quotes.forEach((q) => { const m = String(q.requiredDate || todayPlus(0)).slice(0, 7); months[m] ||= { sales: 0, expenses: 0 }; months[m].sales += quoteCosts(q).total; }); state.expenses.forEach((e) => { const m = String(e.date || todayPlus(0)).slice(0, 7); months[m] ||= { sales: 0, expenses: 0 }; months[m].expenses += Number(e.amount || 0); }); els.monthlyAccounts.innerHTML = Object.entries(months).sort((a, b) => b[0].localeCompare(a[0])).map(([m, t]) => `<tr><td>${esc(m)}</td><td>${money(t.sales)}</td><td>${money(t.expenses)}</td><td><strong>${money(t.sales - t.expenses)}</strong></td></tr>`).join("") || `<tr><td colspan="4">${empty("No monthly totals yet.")}</td></tr>`; }
function saveClient(e) { e.preventDefault(); updateAddressPreview(clientAddressFields()); if (!isUkPostcode(els.clientAddressPostcode.value)) return alert("Please enter the company postcode in a format like N16 6JA."), els.clientAddressPostcode.focus(); state.clients.push({ id: crypto.randomUUID(), company: $("#clientCompany").value.trim(), contact: $("#clientContact").value.trim(), email: $("#clientEmail").value.trim(), phone: $("#clientPhone").value.trim(), site: els.clientSite.value.trim(), notes: $("#clientNotes").value.trim() }); saveState(); els.clientForm.reset(); updateAddressPreview(clientAddressFields()); els.clientDialog.close(); render(); }
function saveQuote(e) { e.preventDefault(); updateAddressPreview(setupAddressFields()); if (!selectedQuoteItems.length) return alert("Add at least one item or service to the quote."); if (!isUkPostcode(els.addressPostcode.value)) return alert("Please enter a UK postcode in a format like N16 6JA."), els.addressPostcode.focus(); state.quotes.unshift({ id: nextQuoteId(), clientId: els.quoteClient.value, premises: els.premises.value.trim(), rooms: Number($("#roomCount").value), workstations: Number($("#workstations").value), requiredDate: $("#requiredDate").value, items: selectedQuoteItems.map((i) => ({ ...i })), notes: $("#quoteNotes").value.trim(), status: "Draft", installStatus: "Not scheduled", installDate: "" }); saveState(); resetQuoteForm(); render(); }
function saveUser(e) { e.preventDefault(); const permissions = $$('input[name="userPermission"]:checked').map((i) => i.value); if (!permissions.length) return alert("Choose at least one page this user can see."); state.users.push({ id: crypto.randomUUID(), name: $("#userName").value.trim(), email: $("#userEmail").value.trim().toLowerCase(), password: $("#userPassword").value, role: $("#userRole").value, permissions, active: $("#userActive").checked }); saveState(); els.userForm.reset(); els.userDialog.close(); render(); }
function saveItem(e) { e.preventDefault(); const item = { id: `item-${crypto.randomUUID()}`, name: $("#itemName").value.trim(), category: $("#itemCategory").value, unitCost: Number($("#itemUnitCost").value), unit: $("#itemUnit").value, defaultQuantity: Number($("#itemDefaultQuantity").value), supplier: $("#itemSupplier").value.trim(), code: $("#itemCode").value.trim(), leadTime: $("#itemLeadTime").value.trim(), description: $("#itemDescription").value.trim(), custom: true }; state.catalog.push(item); if ($("#addItemToCurrentQuote").checked) selectedQuoteItems.push({ ...item, quantity: item.defaultQuantity }); saveState(); els.itemForm.reset(); els.itemDialog.close(); render(); }
function saveExpense(e) { e.preventDefault(); state.expenses.unshift({ id: `expense-${crypto.randomUUID()}`, date: els.expenseDate.value, category: els.expenseCategory.value, payee: els.expensePayee.value.trim(), amount: Number(els.expenseAmount.value), notes: els.expenseNotes.value.trim() }); saveState(); els.expenseForm.reset(); els.expenseDate.value = todayPlus(0); renderAccounting(); }
function deleteExpense(e) { const id = e.target.dataset.deleteExpense; if (!id) return; state.expenses = state.expenses.filter((x) => x.id !== id); saveState(); renderAccounting(); }
function setupAddressFields() { return { line1: els.addressLine1, line2: els.addressLine2, city: els.addressCity, postcode: els.addressPostcode, hidden: els.premises, preview: els.addressPreview, status: els.addressStatus, emptyText: "No setup address entered yet." }; }
function clientAddressFields() { return { line1: els.clientAddressLine1, line2: els.clientAddressLine2, city: els.clientAddressCity, postcode: els.clientAddressPostcode, hidden: els.clientSite, preview: els.clientAddressPreview, status: els.clientAddressStatus, emptyText: "No company address entered yet." }; }
function updateAddressPreview(f) { if (!f.line1 || !f.hidden) return ""; const pc = formatPostcode(f.postcode.value.trim()); if (f.postcode.value && f.postcode.value !== pc) f.postcode.value = pc; const address = [titleCaseWords(f.line1.value.trim()), titleCaseWords(f.line2.value.trim()), titleCaseWords(f.city.value.trim()), pc].filter(Boolean).join(", "); f.hidden.value = address; f.preview.textContent = address || f.emptyText; f.status.textContent = isUkPostcode(pc) ? "Postcode format looks valid. Use Find from postcode to fill the town or city." : "Enter a UK postcode like N16 6JA."; f.status.className = `address-status ${isUkPostcode(pc) ? "is-ok" : ""}`; return address; }
async function lookupPostcodeAddress(f, label) { updateAddressPreview(f); const pc = formatPostcode(f.postcode.value); if (!isUkPostcode(pc)) { f.status.textContent = `Enter a valid ${label} postcode first.`; f.status.className = "address-status is-warn"; return f.postcode.focus(); } f.status.textContent = "Looking up postcode..."; try { const res = await fetch(`https://api.postcodes.io/postcodes/${encodeURIComponent(pc)}`), data = await res.json(); if (!res.ok || !data.result) throw new Error(); if (!f.city.value.trim()) f.city.value = titleCaseWords(data.result.admin_district || data.result.parish || data.result.region || ""); updateAddressPreview(f); f.status.textContent = "Postcode found. Add the building number or street if needed."; f.status.className = "address-status is-ok"; } catch { f.status.textContent = "Could not find that postcode. Check it or enter the address manually."; f.status.className = "address-status is-warn"; } }
function checkAddressOnGoogleMaps() { const address = updateAddressPreview(setupAddressFields()); if (!address) { els.addressStatus.textContent = "Enter an address before checking Google Maps."; els.addressStatus.className = "address-status is-warn"; return; } window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`, "_blank", "noopener"); els.addressStatus.textContent = "Google Maps opened with this address."; els.addressStatus.className = "address-status is-ok"; }
function fillAddressFromText(text) { const parts = String(text || "").split(",").map((p) => p.trim()).filter(Boolean), match = String(text || "").match(/[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}/i); els.addressLine1.value = parts[0] || ""; els.addressLine2.value = parts.length > 3 ? parts.slice(1, -2).join(", ") : ""; els.addressCity.value = parts.length > 1 ? parts[parts.length - 1].replace(match?.[0] || "", "").trim() : ""; els.addressPostcode.value = match ? formatPostcode(match[0]) : ""; updateAddressPreview(setupAddressFields()); }
function addSelectedCatalogItem() { const item = state.catalog.find((i) => i.id === els.catalogSelect.value); if (!item) return; const existing = selectedQuoteItems.find((i) => i.id === item.id); existing ? existing.quantity += 1 : selectedQuoteItems.push({ ...item, quantity: defaultQuantity(item) }); renderSelectedItems(); }
function renderSelectedItems() { els.selectedItems.innerHTML = selectedQuoteItems.length ? selectedQuoteItems.map((i) => `<div class="selected-item" data-item-row="${i.id}"><div><strong>${esc(i.name)}</strong><span>${esc(i.category)} | ${money(i.unitCost)} ${esc(i.unit || "each")}</span></div><label>Qty<input data-item-quantity="${i.id}" min="1" type="number" value="${i.quantity}"></label><label>Unit cost<input data-item-cost="${i.id}" min="0" step="10" type="number" value="${i.unitCost}"></label><strong>${money(i.quantity * i.unitCost)}</strong><button class="icon-btn" data-remove-item="${i.id}" type="button">x</button></div>`).join("") : empty("No items selected yet."); els.quoteTotalPreview.textContent = `Total ${money(quoteCosts({ items: selectedQuoteItems }).total)}`; }
function updateSelectedItemsFromInputs(e) { const id = e.target.dataset.itemQuantity || e.target.dataset.itemCost; if (!id) return; selectedQuoteItems = selectedQuoteItems.map((i) => i.id === id ? { ...i, quantity: e.target.dataset.itemQuantity ? Math.max(1, Number(e.target.value) || 1) : i.quantity, unitCost: e.target.dataset.itemCost ? Math.max(0, Number(e.target.value) || 0) : i.unitCost } : i); renderSelectedItems(); }
function removeSelectedItem(e) { if (!e.target.dataset.removeItem) return; selectedQuoteItems = selectedQuoteItems.filter((i) => i.id !== e.target.dataset.removeItem); renderSelectedItems(); }
function resetQuoteForm() { els.quoteForm.reset(); selectedQuoteItems = ["desk", "task-chair", "onsite-setup"].map((id) => ({ ...state.catalog.find((i) => i.id === id), quantity: id === "onsite-setup" ? 3 : 24 })); $("#requiredDate").value = todayPlus(21); updateAddressPreview(setupAddressFields()); renderSelectedItems(); }
function showQuoteEmail(id) { const q = state.quotes.find((x) => x.id === id), c = getClient(q.clientId), costs = quoteCosts(q); const text = `Hello ${c.contact},\n\nThank you for asking WeSet to quote for your office setup at ${q.premises}.\n\nQuote reference: ${q.id}\nRequired date: ${date(q.requiredDate)}\nTotal estimate: ${money(costs.total)}\n\nKind regards,\nWeSet`; els.quoteEmailText.value = text; els.quoteEmailPreview.innerHTML = `<div class="email-template"><div class="email-body"><p>${esc(text).replaceAll("\n", "<br>")}</p></div></div>`; els.emailQuoteLink.href = `mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(`WeSet quote ${q.id}`)}&body=${encodeURIComponent(text)}`; els.quoteDialog.showModal(); }
function openClientDialog() { updateAddressPreview(clientAddressFields()); els.clientDialog.showModal(); }
function openUserDialog() { els.userForm.reset(); els.userDialog.showModal(); }
function openItemDialog(add) { els.itemForm.reset(); $("#addItemToCurrentQuote").checked = add; els.itemDialog.showModal(); }
function filteredClients() { const q = els.searchInput.value.trim().toLowerCase(); return q ? state.clients.filter((c) => Object.values(c).join(" ").toLowerCase().includes(q)) : state.clients; }
function filteredQuotes() { const q = els.searchInput.value.trim().toLowerCase(); return q ? state.quotes.filter((x) => `${Object.values(x).join(" ")} ${Object.values(getClient(x.clientId)).join(" ")}`.toLowerCase().includes(q)) : state.quotes; }
function updateQuote(id, patch) { state.quotes = state.quotes.map((q) => q.id === id ? { ...q, ...patch } : q); saveState(); render(); }
function getQuote(id) { return state.quotes.find((q) => q.id === id); }
function renderNextAction() { const draft = state.quotes.find((q) => q.status === "Draft"); els.nextAction.textContent = draft ? `Send ${draft.id}` : "Create a quote request"; }
function quoteItems(q) { return q.items || []; }
function quoteCosts(q) { const items = quoteItems(q), supply = items.filter((i) => i.category !== "Services").reduce((s, i) => s + i.quantity * i.unitCost, 0), services = items.filter((i) => i.category === "Services").reduce((s, i) => s + i.quantity * i.unitCost, 0); return { supply, services, total: supply + services }; }
function totalExpenses() { return (state.expenses || []).reduce((s, e) => s + Number(e.amount || 0), 0); }
function defaultQuantity(i) { return ["Desktop computer", "Laptop", "Monitor", "Office desk", "Task chair"].includes(i.name) ? Math.max(1, Number($("#workstations").value) || 1) : i.defaultQuantity || 1; }
function getClient(id) { return state.clients.find((c) => c.id === id) || state.clients[0] || { company: "Client", contact: "", email: "", site: "" }; }
function nextQuoteId() { return `Q-${state.quotes.reduce((m, q) => Math.max(m, Number(String(q.id).replace("Q-", "")) || 1000), 1000) + 1}`; }
function formatPostcode(v) { const c = String(v || "").toUpperCase().replace(/[^A-Z0-9]/g, ""); return c.length <= 3 ? c : `${c.slice(0, -3)} ${c.slice(-3)}`; }
function isUkPostcode(v) { return /^[A-Z]{1,2}\d[A-Z\d]?\s\d[A-Z]{2}$/i.test(formatPostcode(v)); }
function todayPlus(days) { const d = new Date(); d.setDate(d.getDate() + days); return d.toISOString().slice(0, 10); }
function money(v) { return new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(v || 0); }
function date(v) { return v ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${v}T00:00:00`)) : "No date"; }
function titleCaseWords(v) { return String(v || "").replace(/\w\S*/g, (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()); }
function viewLabel(v) { return { dashboard: "Dashboard", clients: "Clients", quotes: "Quote requests", items: "Items", installations: "Installations", accounting: "Accounting", users: "Users" }[v] || v; }
function metric([label, value]) { return `<article class="metric"><span>${esc(label)}</span><strong>${value}</strong></article>`; }
function cls(v) { return String(v || "").replaceAll(" ", "-"); }
function empty(m) { return `<div class="empty">${esc(m)}</div>`; }
function esc(v) { return String(v ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }

